name: Responsive Guard

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  guard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps (ok if none)
        run: npm ci || npm i

      - name: Sanity check placeholder
        run: |
          echo "CI wiring OK ✅ (placeholder step)"
          node -v
          npm -v

      # Optional: try to build if a build script exists; don’t fail if it doesn’t
      - name: Build (optional)
        run: npm run build || echo "No build script yet — skipping"
