name: Responsive Guard

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  guard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps (ok if none)
        run: npm ci || npm i

      - name: Run responsive guard
        run: |
          set -euo pipefail

          echo "1) No legacy JS mobile detection"
          if git grep -nE 'body\.is-mobile|MobileDetector' -- ':!node_modules' || false ; then
            echo "❌ Found legacy mobile detection"; exit 1
          else
            echo "✅ OK"
          fi

          echo "2) Disallowed !important (only allow in visibility gates)"
          if git grep -n '!important' -- ':!node_modules' | grep -vE '\.desktop-only|\.mobile-only' || false ; then
            echo "❌ Found disallowed !important"; exit 1
          else
            echo "✅ OK"
          fi

          echo "3) Viewport-height traps (warn-only)"
          git grep -nE '\b(100vh|100svh|svh|lvh)\b' -- 'app/**/*.css' 'styles/**/*.css' || true

          echo "✅ Responsive guard passed"

      # Optional: try to build if a build script exists; don’t fail if it doesn’t
      - name: Build (optional)
        run: npm run build || echo "No build script yet — skipping"
